spring.application.name=simple-bank-application

server.port=8080

spring.mongodb.uri=mongodb+srv://reedholton_db_user:KGlczFClDNcsho5V@reedmongodbcluster.nddxnfi.mongodb.net/simplebankdb?retryWrites=true&w=majority
